In [1]:
# Import the dependency.
import pandas as pd

In [2]:
# Set the column width
pd.options.display.max_colwidth = 200

#  Read in the dataset.

                                                                orderId,productName,category,sellingPrice,shipping,totalPrice
0                              tb701343926,Exploding Kittens - A Russian Roulette Card Game,Toys & Games,19.99,standard,22.98
1                          jk664905092,Richard Scarry's Cars and Trucks and Things That Go,Children's Books,11.00,2-day,15.99
2  lm255269538,Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps,Sports & Outdoors,26.99,free,26.99
3            cr180186416,Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker,Toys & Games,15.99,standard,18.98
4                                       ef049909573,World of Nintendo Mario Bros U Boo Plush,Video Games,11.99,standard,14.98

In [3]:
# Create a list for the column names.

['orderId,productName,category,sellingPrice,shipping,totalPrice']

In [5]:
# Split the column on the comma and place in a list.

['orderId', 'productName', 'category', 'sellingPrice', 'shipping', 'totalPrice']

In [6]:
# Create a new DataFrame and split the data from one column on the comma into six columns.

,orderId,productName,category,sellingPrice,shipping,totalPrice
0,tb701343926,Exploding Kittens - A Russian Roulette Card Game,Toys & Games,19.99,standard,22.98
1,jk664905092,Richard Scarry's Cars and Trucks and Things That Go,Children's Books,11.00,2-day,15.99
2,lm255269538,Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps,Sports & Outdoors,26.99,free,26.99
3,cr180186416,Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker,Toys & Games,15.99,standard,18.98
4,ef049909573,World of Nintendo Mario Bros U Boo Plush,Video Games,11.99,standard,14.98

In [7]:
# Iterate through the rows, split the values on the comma and then add the values to a list.

[['tb701343926',
  'Exploding Kittens - A Russian Roulette Card Game',
  'Toys & Games',
  '19.99',
  'standard',
  '22.98'],
 ['jk664905092',
  "Richard Scarry's Cars and Trucks and Things That Go",
  "Children's Books",
  '11.00',
  '2-day',
  '15.99'],
 ['lm255269538',
  'Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps',
  'Sports & Outdoors',
  '26.99',
  'free',
  '26.99'],
 ['cr180186416',
  'Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker',
  'Toys & Games',
  '15.99',
  'standard',
  '18.98'],
 ['ef049909573',
  'World of Nintendo Mario Bros U Boo Plush',
  'Video Games',
  '11.99',
  'standard',
  '14.98']]

In [8]:
# Create a new DataFrame with the `data=` attribute equal to the list of row values
# and the `columns=` attribute equal to the list of column names.

,orderId,productName,category,sellingPrice,shipping,totalPrice
0,tb701343926,Exploding Kittens - A Russian Roulette Card Game,Toys & Games,19.99,standard,22.98
1,jk664905092,Richard Scarry's Cars and Trucks and Things That Go,Children's Books,11.00,2-day,15.99
2,lm255269538,Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps,Sports & Outdoors,26.99,free,26.99
3,cr180186416,Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker,Toys & Games,15.99,standard,18.98
4,ef049909573,World of Nintendo Mario Bros U Boo Plush,Video Games,11.99,standard,14.98

In [9]:
# Get the index datatype, column names.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   orderId       5 non-null      object
 1   productName   5 non-null      object
 2   category      5 non-null      object
 3   sellingPrice  5 non-null      object
 4   shipping      5 non-null      object
 5   totalPrice    5 non-null      object
dtypes: object(6)
memory usage: 368.0+ bytes

In [10]:
# Convert sellingPrice and totalPrice to a float datatype.

,orderId,productName,category,sellingPrice,shipping,totalPrice
0,tb701343926,Exploding Kittens - A Russian Roulette Card Game,Toys & Games,19.99,standard,22.98
1,jk664905092,Richard Scarry's Cars and Trucks and Things That Go,Children's Books,11.00,2-day,15.99
2,lm255269538,Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps,Sports & Outdoors,26.99,free,26.99
3,cr180186416,Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker,Toys & Games,15.99,standard,18.98
4,ef049909573,World of Nintendo Mario Bros U Boo Plush,Video Games,11.99,standard,14.98

In [11]:
# Get the index datatype, column names.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   orderId       5 non-null      object
 1   productName   5 non-null      object
 2   category      5 non-null      object
 3   sellingPrice  5 non-null      float64
 4   shipping      5 non-null      object
 5   totalPrice    5 non-null      float64
dtypes: float64(2), object(4)
memory usage: 368.0+ bytes

In [12]:
# Get the column names.

Index(['orderId', 'productName', 'category', 'sellingPrice', 'shipping',
       'totalPrice'],
      dtype='object')

In [13]:
# Calculate the shipping price of each product and add it to a new column.

,orderId,productName,category,sellingPrice,shipping,totalPrice,shippingPrice
0,tb701343926,Exploding Kittens - A Russian Roulette Card Game,Toys & Games,19.99,standard,22.98,2.99
1,jk664905092,Richard Scarry's Cars and Trucks and Things That Go,Children's Books,11.00,2-day,15.99,4.99
2,lm255269538,Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps,Sports & Outdoors,26.99,free,26.99,0.00
3,cr180186416,Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker,Toys & Games,15.99,standard,18.98,2.99
4,ef049909573,World of Nintendo Mario Bros U Boo Plush,Video Games,11.99,standard,14.98,2.99

In [14]:
# Reorder the columns ['orderId', 'productName', 'category', 'sellingPrice','shippingPrice', 'totalPrice', 'shipping']

,orderId,productName,category,sellingPrice,shippingPrice,totalPrice,shipping
0,tb701343926,Exploding Kittens - A Russian Roulette Card Game,Toys & Games,19.99,2.99,22.98,standard
1,jk664905092,Richard Scarry's Cars and Trucks and Things That Go,Children's Books,11.00,4.99,15.99,2-day
2,lm255269538,Kootek Camping Hammock Double & Single Portable Hammocks with 2 Tree Straps,Sports & Outdoors,26.99,0.00,26.99,free
3,cr180186416,Swing Set Stuff Climbing Rope with Steps (Blue) & SSS Logo Sticker,Toys & Games,15.99,2.99,18.98,standard
4,ef049909573,World of Nintendo Mario Bros U Boo Plush,Video Games,11.99,2.99,14.98,standard